cms: &cms
  adapter: <%= defined?(Mysql2) ? 'mysql2' : 'mysql' %>
  database: reactor_cms
  username: reactor
  password: reactor
  host: 127.0.0.1
  reconnect: true

test:
  <<: *cms

development:
  #<<: *cms
  adapter: <%= defined?(Mysql2) ? 'mysql2' : 'mysql' %>
  database: test
  username: root
  password: root
  host: 127.0.0.1
  reconnect: true
