cms: &cms
  adapter: <%= defined?(Mysql2) ? 'mysql2' : 'mysql' %>
  database: reactor
  username: reactoruser
  password: reactoruser
  host: 33.33.33.10
  reconnect: true

test:
  <<: *cms

development:
  <<: *cms
